%YAML:1.0

recvInstances:
    - name: chassis
      type: chassis_proxy
      id: 1
    - name: imu
      type: imu_proxy
      id: 1
    - name: gnss_info
      type: gnss_info_proxy
      id: 1
    - name: nnp_cam_lane
      type: lanes_proxy
      id: 1
    - name: plugin
      type: location_node_info_proxy
      id: 104

sendInstances:
    - name: npp_debug_msg_30
      type: debug_protobuf_skeleton
      id: 30
    - name: npp_debug_msg_31
      type: debug_protobuf_skeleton
      id: 31
    - name: npp_debug_msg_32
      type: debug_protobuf_skeleton
      id: 32

log:
    name: mal
    description: mapping
    # 注意：必须这个路径，不然打不出来
    file: /opt/usr/log/hz_log
    mode: 0 #mode: 日志模式 |0-remote日志，异步日志|1-console日志，同步日志|2-本地文件存储日志，同步日志|3-remote+console日志|4-remote+本地文件存储日志|5-console+本地文件存储日志|6-remote+console+本地文件存储日志
    level: 4 #日志等级 0: verbose, 1: debug, 2: info, 3: warn, 4: error, 5: fatal, 6: off

# trigger二选一即可
trigger:
    - name: ChassisImuCB
      type: EVENT
      mainSources:
          - name: chassis
            timeout: 1000
          - name: imu
            timeout: 1000
    - name: LaneCB
      type: EVENT
      mainSources:
          - name: nnp_cam_lane
            timeout: 1000
    - name: plugin_cb
      type: EVENT
      mainSources:
          - name: plugin
            timeout: 100
    - name: map_service_cycle_cb
      type: PERIOD
      period: 100
    - name: map_fusion_cycle_cb
      type: PERIOD
      period: 100

