%YAML:1.0

library: "${ADFLITE_ROOT_PATH}/../../depend/nos/x86_2004/lib/libadf-lite-ds.so"
depLibPath: ["${ADFLITE_ROOT_PATH}/lib/"]
executorName: DataSource

log:
  level: 2

dataSourcesIn:
  - topic: imu_ins            # 外部topic名称转成内部topic名称
    type: proto_proxy
    cmTopic: /soc/imuinsinfo  # 外部订阅topic名称
    cmDomainId: 0
  - topic: inspva
    type: proto_proxy
    cmTopic: /localization/location_node
    cmDomainId: 0
#  - topic: gnssinfo
#    type: proto_proxy
#    cmTopic: /soc/gnssinfo
#    cmDomainId: 0
  - topic: chassis
    type: proto_proxy
    cmTopic: /soc/chassis
    cmDomainId: 0
  - topic: percep_detection
    type: proto_proxy
    cmTopic: /perception/fsd/onboard/detection
    cmDomainId: 0
  - topic: percep_obj
    type: proto_proxy
    cmTopic: /perception/fsd/obj_fusion_1 
    cmDomainId: 0
  - topic: camera_0
    type: idl_proxy
    cmTopic: /soc/zerocopy/camera_0
    cmDomainId: 0
#  - topic: tlr_percep
#    type: proto_proxy
#    cmTopic: /perception/fsd/environment/tlr_msg
#    cmDomainId: 0
  - topic: localization
    type: proto_proxy
    cmTopic: /localization/location
    cmDomainId: 0
  - topic: map_fusion
    type: proto_proxy
    cmTopic: /localization/fusionmap
    cmDomainId: 0
  - topic: dr
    type: proto_proxy
    cmTopic: /localization/deadreckoning
    cmDomainId: 0
  - topic: percep_transport
    type: proto_proxy
    cmTopic: /perception/fsd/transportelement_1
    cmDomainId: 0
  - topic: local_map
    type: proto_proxy
    cmTopic: /localization/local_map
    cmDomainId: 0
  - topic: pe
    type: proto_proxy
    cmTopic: /localization/pe
    cmDomainId: 0
#  - topic: tlr_fusion
#    type: proto_proxy
#    cmTopic: /mapping/junction_passable
#    cmDomainId: 0
  - topic: driving_status
    type: proto_proxy
    cmTopic: /planning/ego_trajectory
    cmDomainId: 0
