%YAML:1.0

library: "${ADFLITE_ROOT_PATH}/runtime_service/mapping/lib/libmapping_onboard_lite_fc.so"
depLibPath: ["${ADFLITE_ROOT_PATH}/lib", "${ADFLITE_ROOT_PATH}/runtime_service/mapping/lib"]
executorName: FusionCenterLite

input:
  - topic: imu_ins
    capacity: 2
  - topic: chassis
    capacity: 2
  - topic: /location/ins_fusion
    capacity: 2
  - topic: dr
    capacity: 2
  - topic: /location/pose_estimation
    capacity: 2
  - topic: running_mode 
    capacity: 2


output:
  - topic: localization

trigger:
  - name: recv_ins_fusion
    type: EVENT
    mainSources:
      - name: /location/ins_fusion
        timeout: 100
  - name: recv_mm
    type: EVENT
    mainSources:
      - name: /location/pose_estimation
        timeout: 1000
  - name: recv_dr
    type: EVENT
    mainSources:
      - name: dr
        timeout: 100
  - name: recv_running_mode
    type: EVENT
    mainSources:
      - name: running_mode
        timeout: 1000
  - name: recv_imu
    type: EVENT
    mainSources:
      - name: imu_ins
        timeout: 1000
  - name: recv_chassis
    type: EVENT
    mainSources:
      - name: chassis
        timeout: 1000