%YAML:1.0

library: "${ADFLITE_ROOT_PATH}/runtime_service/mapping/lib/libmapping_onboard_lite_pose_estimation.so"
depLibPath: ["${ADFLITE_ROOT_PATH}/lib", "${ADFLITE_ROOT_PATH}/runtime_service/mapping/lib"]
executorName: PoseEstimationLite

input:
  - topic: /location/ins_fusion
    capacity: 2
  - topic: percep_transport
    capacity: 2
 # - topic: [map topic]
 #   capacity: 
output:
  - topic: /location/pose_estimation

trigger:
  - name: send_pose_estimation_result
    type: PERIOD
    period: 10
  - name: recv_ins_fusion
    type: EVENT
    mainSources:
      - name: /location/ins_fusion
        timeout: 100

 # - name: receive_map_message
 #   type: EVENT
 #   mainSources:
 #     - name: imu_ins
 #       timeout: 100
  
  - name: recv_perception
    type: EVENT
    mainSources:
      - name: percep_transport
        timeout: 100
