%YAML:1.0

library: "${ADFLITE_ROOT_PATH}/runtime_service/mapping/lib/libmapping_onboard_lite_fc.so"
depLibPath: ["${ADFLITE_ROOT_PATH}/lib", "${ADFLITE_ROOT_PATH}/runtime_service/mapping/lib"]
executorName: FusionCenterLite

input:
  - topic: imu_ins
    capacity: 2
  - topic: /location/ins_fusion
    capacity: 2
  - topic: /location/dr_fusion
    capacity: 2
  - topic: /location/pose_estimation
    capacity: 2
  - topic: local_map
    capacity: 2
  - topic: running_mode 
    capacity: 2


output:
  - topic: localization

trigger:
  - name: recv_ins_fusion
    type: EVENT
    mainSources:
      - name: /location/ins_fusion
        timeout: 100
  - name: recv_pose_estimation
    type: EVENT
    mainSources:
      - name: /location/pose_estimation
        timeout: 1000
  - name: recv_dr_fusion
    type: EVENT
    mainSources:
      - name: /location/dr_fusion
        timeout: 100
  - name: recv_running_mode
    type: EVENT
    mainSources:
      - name: running_mode
        timeout: 1000
  - name: recv_local_map
    type: EVENT
    mainSources:
      - name: local_map
        timeout: 1000