%YAML:1.0

library: "${ADFLITE_ROOT_PATH}/runtime_service/mapping/lib/libmapping_onboard_lite_ins_fusion.so"
depLibPath: ["${ADFLITE_ROOT_PATH}/lib", "${ADFLITE_ROOT_PATH}/runtime_service/mapping/lib"]
executorName: InsFusionLite

input:
  - topic: imu_ins
    capacity: 2
  - topic: inspva
    capacity: 2
  - topic: running_mode 
    capacity: 2
  - topic: gnssinfo
    capacity: 2

output:
  - topic: /location/ins_fusion

trigger:
  - name: receive_inspva
    type: EVENT
    mainSources:
      - name: inspva
        timeout: 100
  - name: receive_ins
    type: EVENT
    mainSources:
      - name: imu_ins
        timeout: 100
  - name: receive_gnss
    type: EVENT
    mainSources:
      - name: gnssinfo
        timeout: 1000
  - name: recv_running_mode
    type: EVENT
    mainSources:
      - name: running_mode
        timeout: 1000
