%YAML:1.0

library: "${ADFLITE_ROOT_PATH}/runtime_service/mapping/lib/libmapping_onboard_lite_mf.so"
depLibPath: ["${ADFLITE_ROOT_PATH}/lib", "${ADFLITE_ROOT_PATH}/runtime_service/mapping/lib"]
executorName: MapFusionLite

input:
    - topic: localization 
      capacity: 5
    - topic: /location/ins_fusion 
      capacity: 5
    - topic: local_map
      capacity: 5
    - topic: running_mode 
      capacity: 5
    - topic: percep_transport 
      capacity: 5
    - topic: dr 
      capacity: 5
    - topic: function_manager_in 
      capacity: 5
    - topic: percep_obj 
      capacity: 5
    - topic: dv_nav_data 
      capacity: 5

output:
  - topic: map_fusion
  - topic: routing_response
  - topic: map_select_dbg

trigger:
    - name: recv_location
      type: EVENT
      mainSources:
      
        - name: localization
          timeout: 100
    - name: recv_local_map
      type: EVENT
      mainSources:
        - name: local_map
          timeout: 1000
    - name: recv_loc_plugin
      type: EVENT
      mainSources:
        - name: /location/ins_fusion
          timeout: 100
    - name: send_map_fusion
      type: PERIOD
      period: 100
    - name: recv_running_mode
      type: EVENT
      mainSources:
        - name: running_mode
          timeout: 1000
    - name: recv_percep_transport
      type: EVENT
      mainSources:
        - name: percep_transport
          timeout: 1000
    - name: recv_dr
      type: EVENT
      mainSources:
        - name: dr
          timeout: 100
    - name: recv_fct_in
      type: EVENT
      mainSources:
        - name: function_manager_in
          timeout: 100
    - name: recv_percep_obj
      type: EVENT
      mainSources:
        - name: percep_obj
          timeout: 1000
    - name: recv_dv_nav_data
      type: EVENT
      mainSources:
        - name: dv_nav_data
          timeout: 1000