%YAML:1.0

library: "${ADFLITE_ROOT_PATH}/runtime_service/mapping/lib/libmapping_mf_lite.so"
depLibPath: ["${ADFLITE_ROOT_PATH}/lib", "${ADFLITE_ROOT_PATH}/runtime_service/mapping/lib"]
executorName: PriorProviderLite

input:
  - topic: loc_plugin # in-process cm
    capacity: 5

trigger:
  - name: on_loc_plugin
    type: EVENT
    mainSources:
      - name: loc_plugin
        timeout: 1000
