%YAML:1.0

library: "${ADFLITE_ROOT_PATH}/runtime_service/mapping/lib/libmapping_onboard_lite_mf.so"
depLibPath: ["${ADFLITE_ROOT_PATH}/lib", "${ADFLITE_ROOT_PATH}/runtime_service/mapping/lib"]
executorName: TlrFusionLite

input:
  - topic: tlr_percep
    capacity: 5
  - topic: running_mode 
    capacity: 5

output:
  - topic: tlr_fusion

trigger:
  - name: recv_tlr_percep
    type: EVENT
    mainSources:
      - name: tlr_percep
        timeout: 1000
  - name: recv_running_mode
    type: EVENT
    mainSources:
      - name: running_mode
        timeout: 1000
