%YAML:1.0

library: "${ADFLITE_ROOT_PATH}/runtime_service/mapping/lib/libonboard_lite_laneline_postprocess.so"
depLibPath: ["${ADFLITE_ROOT_PATH}/lib", "${ADFLITE_ROOT_PATH}/runtime_service/mapping/lib"]
executorName: EnvBevfusionOnboard

input:
    - topic: percep_detection
      capacity: 5
    - topic: dr 
      capacity: 5
    - topic: /localization/deadreckoning 
      capacity: 5

output:
    - topic: /perception/fsd/transportelement_1

trigger:
  - name: recv_detection_bevfusion_lane_proto
    type: EVENT
    timeWindow: 1000
    mainSources:
      - name: percep_detection
        timeout: 1000
  - name: recv_dr
    type: EVENT
    mainSources:
      - name: dr
        timeout: 1000
  - name: recv_dr_proto
    type: EVENT
    mainSources:
      - name: /localization/deadreckoning
        timeout: 1000
