%YAML:1.0

library: "/app/lib/libadf-lite-ds.so"
depLibPath: ["/app/lib/"]
executorName: DataSource

log:
  level: 2

dataSourcesIn:
  - topic: imu_ins            # 外部topic名称转成内部topic名称
    type: proto_proxy
    cmTopic: /soc/imuinsinfo  # 外部订阅topic名称
    cmDomainId: 0
  - topic: inspva
    type: proto_proxy
    cmTopic: /localization/location_node
    cmDomainId: 0
  - topic: gnssinfo
    type: proto_proxy
    cmTopic: /soc/gnssinfo
    cmDomainId: 0
  - topic: chassis
    type: proto_proxy
    cmTopic: /soc/chassis
    cmDomainId: 0
  - topic: percep_detection
    type: proto_proxy
    cmTopic: /perception/fsd/onboard/detection
    cmDomainId: 0
  - topic: percep_freespace
    type: proto_proxy
    cmTopic: /perception/fsd/freespace_1
    cmDomainId: 0
  - topic: tlr_percep
    type: proto_proxy
    cmTopic: /perception/fsd/environment/tlr_msg
    cmDomainId: 0
  - topic: function_manager_in
    type: proto_proxy
    cmTopic: /soc/mcu2ego 
    cmDomainId: 0
  - topic: driving_status
    type: proto_proxy
    cmTopic: /planning/ego_trajectory
    cmDomainId: 0
  - topic: percep_obj
    type: proto_proxy
    cmTopic: /perception/fsd/obj_fusion_1 
    cmDomainId: 0

dataSourcesOut:
  - topic: localization
    capacity: 5
    type: proto_skeleton
    cmTopic: /localization/location
    cmDomainId: 0
  - topic: map_fusion
    capacity: 5
    type: proto_skeleton
    cmTopic: /localization/fusionmap
    cmDomainId: 0
  - topic: dr
    capacity: 5
    type: proto_skeleton
    cmTopic: /localization/deadreckoning
    cmDomainId: 0
  - topic: percep_transport
    capacity: 5
    type: proto_skeleton
    cmTopic: /perception/fsd/transportelement_1
    cmDomainId: 0
  - topic: percep_transport_lm
    capacity: 5
    type: proto_skeleton
    cmTopic: /perception/fsd/transportelement_lm
    cmDomainId: 0
  - topic: local_map
    capacity: 5
    type: proto_skeleton
    cmTopic: /localization/local_map
    cmDomainId: 0
  - topic: /location/pose_estimation
    capacity: 5
    type: proto_skeleton
    cmTopic: /localization/pe
    cmDomainId: 0
  - topic: /location/ins_fusion
    capacity: 5
    type: proto_skeleton
    cmTopic: /localization/ins_fusion
    cmDomainId: 0
  - topic: tlr_fusion
    capacity: 5
    type: proto_skeleton
    cmTopic: /mapping/junction_passable
    cmDomainId: 0
  - topic: map_select_dbg
    capacity: 5
    type: proto_skeleton
    cmTopic: /mapping/map_select_dbg
    cmDomainId: 0
