%YAML:1.0

library: "${ADFLITE_ROOT_PATH}/runtime_service/mapping/lib/libonboard_lite_localmapping.so"
depLibPath: ["${ADFLITE_ROOT_PATH}/lib/", "${ADFLITE_ROOT_PATH}/runtime_service/mapping/lib"]
executorName: LocalMappingOnboard

input:
    - topic: percep_transport
      capacity: 5
    - topic: localization 
      capacity: 5
    - topic: lm_image 
      capacity: 5
    - topic: running_mode 
      capacity: 5


trigger:
  - name: recv_laneline
    type: EVENT
    mainSources:
      - name: percep_transport
        timeout: 1000
  - name: recv_localization
    type: EVENT
    mainSources:
      - name: localization
        timeout: 1000
  - name: recv_image
    type: EVENT
    mainSources:
      - name: lm_image
        timeout: 1000
  - name: recv_running_mode
    type: EVENT
    mainSources:
      - name: running_mode
        timeout: 1000
  
  - name: send_lm # send workresult1,workresult2
    type: PERIOD
    period: 100
