%YAML:1.0

library: "${ADFLITE_ROOT_PATH}/runtime_service/mapping/lib/libonboard_lite_localmapping.so"
depLibPath: ["${ADFLITE_ROOT_PATH}/lib/", "${ADFLITE_ROOT_PATH}/runtime_service/mapping/lib"]
executorName: LocalMappingOnboard

input:
    - topic: dr 
      capacity: 5
    - topic: percep_detection
      capacity: 5
    - topic: localization 
      capacity: 5
    - topic: camera_0 
      capacity: 5
    - topic: running_mode 
      capacity: 5

# output:
#     - topic: /perception/fsd/transportelement_1

trigger:
  - name: recv_perception
    type: EVENT
    timeWindow: 1000
    mainSources:
      - name: percep_detection
        timeout: 1000
  - name: recv_dr
    type: EVENT
    mainSources:
      - name: dr
        timeout: 1000
  - name: recv_localization
    type: EVENT
    mainSources:
      - name: localization
        timeout: 1000
  - name: recv_image
    type: EVENT
    mainSources:
      - name: camera_0
        timeout: 1000
  - name: recv_running_mode
    type: EVENT
    mainSources:
      - name: running_mode
        timeout: 1000
