
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CROSS_SDK_ROOT /usr/local/orin_sdk/)

set(CMAKE_C_COMPILER ${CROSS_SDK_ROOT}/aarch64/bin/aarch64-linux-gcc)
set(CMAKE_CXX_COMPILER ${CROSS_SDK_ROOT}/aarch64/bin/aarch64-linux-g++)

set(CMAKE_FIND_ROOT_PATH ${CROSS_SDK_ROOT} ${CMAKE_INSTALL_PREFIX})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)