%YAML:1.0

library: "${ADFLITE_ROOT_PATH}/runtime_service/mapping/lib/libonboard_lite_dr.so"
depLibPath: ["${ADFLITE_ROOT_PATH}/lib", "${ADFLITE_ROOT_PATH}/runtime_service/mapping/lib"]
executorName: DeadReckoning

input:
    - topic: imu_ins # in-process cm
      capacity: 5
    - topic: chassis # interprocess cm
      capacity: 5

trigger:
  - name: dr_proc # send workresult1,workresult2
    type: PERIOD
    period: 10

  - name: receive_imu_chassis
    type: EVENT
    mainSources:
      - name: imu_ins
        timeout: 1000
      - name: chassis
        timeout: 1000
