%YAML:1.0

recv_imu: true
recv_ins: true
recv_dr: true
recv_pe: true
imu_deque_max_size: 10
ins_deque_max_size: 25100
dr_deque_max_size: 300
pe_deque_max_size: 10

passthrough_ins: false

ins_init_status:    # INS初始化的正常状态
  - sys_status: 2
    gps_status: 4

refpoint_update_dist: 20000.0 #refpoint切换距离-m
search_state_cnt: 45  # 在该帧数内有mm测量，loc = 2
# 使用INS对MM进行补帧
use_ins_predict_mm: false
no_mm_min_time: 0.5  # 超过min_time无mm测量，使用ins进行补帧
no_mm_max_time: 250    # s,超过max_time无mm测量，直接使用ins测量
no_mm_max_dis: 200    # m,超过max_dis无mm测量，直接使用ins测量
# ESKF时加入DR测量
use_dr_measurement: false
# fc线程频率
run_fusion_interval_ms: 10
window_size: 100      # fc队列长度
smooth_outputs: true # 开启KF平滑滤波
use_smooth_yaw: true
# fc使用txt调试mm,fc与INS差值
use_debug_txt: false
# LOC=2、5 进入退出协方差限制条件 * 1e-10
loc2_posx_conv: 65.0
loc2_posy_conv: 65.0
loc2_yaw_conv: 0.11
exit_multiple: 8

require_local_pose: false
lateral_error_compensation: false
max_dr_pe_horizontal_dist_error: 1.0
max_dr_pe_heading_error: 5
max_fc_pe_horizontal_dist_error: 0.5