%YAML:1.0
# imu预测
imu_noise_v_x: 8.3e-4
imu_noise_v_y: 8.3e-4
imu_noise_v_z: 8.3e-4
imu_noise_ori_x: 2.9e-4
imu_noise_ori_y: 2.9e-4
imu_noise_ori_z: 2.9e-4

# mm观测
use_mm: true
mm_noise_x: 1e-2           # 1cm
mm_noise_y: 1e-2           # 1cm
mm_noise_z: 1e-2           # 1cm
mm_noise_ori_x: 1.7e-4     # 0.1度 0.1/180*pi=0.0017
mm_noise_ori_y: 1.7e-4     # 0.1度
mm_noise_ori_z: 1.7e-4     # 0.01度

# ins观测
use_ins: true
ins_noise_x: 5e-2
ins_noise_y: 5e-2
ins_noise_z: 5e-2
ins_noise_ori_x: 5e-4
ins_noise_ori_y: 5e-4
ins_noise_ori_z: 5e-4

# chassis观测
use_chassis: true
chassis_noise_v_x: 1e-1    # 0.1m/s
chassis_noise_v_y: 1e-1
chassis_noise_v_z: 1e-1