%YAML:1.0

library: "${ADFLITE_ROOT_PATH}/runtime_service/mapping/lib/libmapping_onboard_global_lite.so"
depLibPath: ["${ADFLITE_ROOT_PATH}/lib", "${ADFLITE_ROOT_PATH}/runtime_service/mapping/lib"]
executorName: GlobalLite

input:
  - topic: lm_image
    capacity: 5

trigger:
  - name: on_front_narrow_img
    type: EVENT
    mainSources:
      - name: lm_image
        timeout: 1000
