%YAML:1.0

library: "/media/ni/2T/workspace/toqingluan/mapping2/mapping/release/x86/lib/libadf-lite-ds.so"
depLibPath: ["/media/ni/2T/workspace/toqingluan/mapping2/mapping/release/x86/lib/"]
executorName: DataSource

log:
    level: 2

dataSourcesIn:
    - topic: ImuInfo     #外部topic名称转成内部topic名称
      type: proto_proxy
      cmTopic: ImuInfo   #外部订阅topic名称
      cmDomainId: 0

    - topic: Inspva
      type: proto_proxy
      cmTopic: LocPlugin
      cmDomainId: 0

dataSourcesOut:
    - topic: InsFusion
      type: proto_skeleton
      cmTopic: InsFusion
      cmDomainId: 0