%YAML:1.0

#basic
use_lane_line: true
use_pole: true
use_traffic_sign: true
delay_frame: 2
max_frame_buf: 8   
use_smooth: false
use_interpolate: false
map_crop_front: 1550.0
map_crop_width: 300.0
map_distance: 150
# cyber_topic
lane_line_topic: "/perception/fsd/transportelement_1"
node_info_topic: "/mapping/location/pose_estimate"
ins_topic: "/mapping/location/ins"
# deque size
ins_deque_max_size: 500
fc_deque_max_size: 500

# fault diagnosis
# Fault Switch
use_fc_exceed_curb_fault: true        #fault-114
use_valid_pecep_lane_fault: true      #fault-123
use_valid_map_lane_fault: true        #fault-124
use_fc_offset_onelane_fault: true     #fault-125
use_map_lane_match_fault: true        #fault-130
##no valid fault
use_valid_estimate_last_fault: false  #已关闭(old fault-125)
##map_lane_match_fault
map_lane_match_diver: 2.0       # 一分二改道的阈值
map_lane_match_max: 0.4         # 最大y_error(m)--阈值0.4
map_lane_match_buff: 20         # 超过buff次就上报故障
map_lane_match_ser_max: 0.8     # 阈值0.8
map_lane_match_ser_buff: 5
near_dis: 2                     # 近段点距离
straight_far_dis: 25            # 直道远段点距离
curve_far_dis: 12               # 匝道远段点距离
curvature_thr: 0.0005           # 感知车道线曲率阈值
min_vel: 7                      # 低速阈值 m/s
##valid_estimate_last_fault
valid_estimate_last_buff: 100   # 持续valid_estimate_buff_* 0.033s
invalid_estimate_last_buff: 3   # 失效invalid_estimate_buff_ * 0.033s
estimate_last_error_buff: 10    # 错误持续buff * 0.033s，即清空
##valid_estimate_fault
estimate_buff: 3
##fc_exceed_curb_fault
exceed_curb_report_cnt: 10
##fc_offset_onelane
offset_onelane_max_err: 3       # m 
offset_onelane_cnt: 30
offset_maplane_min_dis: -20     # m，车道线最近距离
offset_maplane_max_dis: 40      # m，车道线最远距离 
offset_maxlane: 9               # m，车道线阈值，只使用9m内的车道线
##valid_pecep_lane_fault(123)
invalid_pecep_thr: 1            # s，秒
##valid_map_lane_fault(124)
invalid_map_thr: 1              # s，秒    

# perception lane config
lane_confidence_thre: 0.5
lane_rviz_show_onlyvalid: true

# about solve weight
solve_weight: 1.57 # PI_2
solve_point2line_base: 0.8

# check lane_match
thre_continue_badmatch: 3
thre_delta_y_diff: 0.1

perceplane_len_lowerbound: 1.0

# change refer point
can_ref_point_changed: true
thre_ref_point_change: 20000

# temporary strategy: history reason,
# TDDO: change to 'true' after test
use_ll_perceplane: true

#rviz
rviz_show_map_centerlane: false
rviz_show_pceplane_oriT: false

# about debug
debug_plot_info: false

line_error_normal_thr: 0.15

use_rviz_bridge: false

# double line type point weight
set_point_weight_switch: true
double_line_point_weight: 0.3
recur_input_in_ins_rtk_smooth: true
recur_input_x_thr: 3

# lane width check
lane_width_diff_thre: 0.35
lane_width_diff_thre_offset: 0.07
lane_width_check_switch: true
max_pair_count_thre: 10
min_pair_count_thre: 3

# filter point pairs
avg_diff_offset: 0.25
window_size: 10

# adjust left or right pairs weight
adjust_weight_by_lane_width_check: true
min_lane_width_check_thre: 0.20
max_lane_width_check_thre: 0.35

# match perception line length
common_max_line_length: 50.0
common_min_line_length: 2.0

max_length_offset: 20.0

curvature_thresold: 0.05