std_msgs/Header header

rviz_msgs/Header proto_header

rviz_msgs/WheelSpeed wheel_speed
rviz_msgs/WheelCounter wheel_counter

int32 GearPosition_GEAR_NEUTRAL = 0
int32 GearPosition_GEAR_DRIVE = 1
int32 GearPosition_GEAR_REVERSE = 2
int32 GearPosition_GEAR_PARKING = 3
int32 GearPosition_GEAR_LOW = 4
int32 GearPosition_GEAR_INVALID = 5
int32 GearPosition_GEAR_NONE = 6
# GearPosition
int32 gear_location