int32 WheelSpeedType_FORWARD = 0
int32 WheelSpeedType_BACKWARD = 1
int32 WheelSpeedType_STANDSTILL = 2
int32 WheelSpeedType_INVALID = 3

bool is_wheel_spd_rr_valid
# WheelSpeedType
int32 wheel_direction_rr
float64 wheel_spd_rr
bool is_wheel_spd_rl_valid
# WheelSpeedType
int32 wheel_direction_rl
float64 wheel_spd_rl
bool is_wheel_spd_fr_valid
# WheelSpeedType
int32 wheel_direction_fr
float64 wheel_spd_fr
bool is_wheel_spd_fl_valid
# WheelSpeedType
int32 wheel_direction_fl
float64 wheel_spd_fl
